version: "3.8"

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - vesselmonitoring_appnet

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - vesselmonitoring_appnet

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - vesselmonitoring_appnet

  hdfs-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-namenode
    ports:
      - "9870:9870"  # Web UI for HDFS
      - "9000:9000"  # HDFS service port
    environment:
      - CLUSTER_NAME=hadoop-cluster
    volumes:
      - hdfs-namenode-data:/hadoop/dfs/name
    networks:
      - vesselmonitoring_appnet

  hdfs-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: hdfs-datanode
    depends_on:
      - hdfs-namenode
    environment:
      - CLUSTER_NAME=hadoop-cluster
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:9000
    volumes:
      - hdfs-datanode-data:/hadoop/dfs/data
    networks:
      - vesselmonitoring_appnet

volumes:
  cassandra-data:
  hdfs-namenode-data:
  hdfs-datanode-data:

networks:
  vesselmonitoring_appnet:
    driver: bridge
